include ../../problems.mk

test: $(TARGETS)
	./1 < input-sample-1 > got
	echo 1 > expected
	diff -u got expected
	@#
	./1 < input-sample-2 > got
	echo 6 > expected
	diff -u got expected
	@#
	./1 < input-sample-3 > got
	echo 5 > expected
	diff -u got expected
	@#
	./1 < input-sample-4 > got
	echo 16 > expected
	diff -u got expected
	@#
	./1 < input-sample-5 > got
	echo 1 > expected
	diff -u got expected
	@#
	./1 < input-sample-6 > got
	echo 9 > expected
	diff -u got expected
	@#
	./1 < input-sample-7 > got
	echo 9 > expected
	diff -u got expected
	@#
	./1 < input-sample-8 > got
	echo 3 > expected
	diff -u got expected
	@#
	./1 < input > got
	echo 8337 > expected
	diff -u got expected
	@#
	./2 < input-sample-9 > got
	echo 0 > expected
	diff -u got expected
	@#
	./2 < input-sample-10 > got
	echo 17 > expected
	diff -u got expected
	@#
	./2 < input-sample-11 > got
	echo 3 > expected
	diff -u got expected
	@#
	./2 < input-sample-12 > got
	echo 2 > expected
	diff -u got expected
	@#
	./2 < input-sample-13 > got
	echo 0 > expected
	diff -u got expected
	@#
	./2 < input-sample-14 > got
	echo 0 > expected
	diff -u got expected
	@#
	./2 < input-sample-15 > got
	echo 10 > expected
	diff -u got expected
	@#
	./2 < input > got
	echo 4330 > expected
	diff -u got expected
	@#
	rm got expected
